import { styles } from '../../../ki-frame/src/domBuilderStyles'

export const pageStyles = {
  stack: styles({ display: 'flex', flexDirection: 'column', gap: '22px' }),
  denseStack: styles({ display: 'flex', flexDirection: 'column', gap: '10px' }),
  gridTwo: styles({ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: '12px' }),
  mainSection: styles({ display: 'flex', flexDirection: 'column', gap: '14px' }),
  mainSectionHeader: styles({
    display: 'flex',
    gap: '12px',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    padding: '14px 16px',
    border: '1px solid rgba(15, 23, 42, 0.08)',
    borderRadius: '8px',
    backgroundColor: 'rgba(15, 23, 42, 0.02)',
  }),
  mainSectionHeaderText: styles({ display: 'flex', flexDirection: 'column', gap: '6px', flex: '1 1 360px' }),
  mainSectionSummary: styles({ margin: '0', color: 'rgb(75, 85, 99)' }),
  mainSectionMetrics: styles({ display: 'flex', gap: '8px', flexWrap: 'wrap' }),
  mainSectionMetric: styles({
    display: 'flex',
    alignItems: 'baseline',
    gap: '6px',
    padding: '6px 10px',
    borderRadius: '8px',
    backgroundColor: '#fff',
    border: '1px solid rgba(15, 23, 42, 0.08)',
  }),
  mainSectionMetricLabel: styles({ color: 'rgb(75, 85, 99)', fontSize: '12px' }),
  mainSectionContent: styles({ display: 'flex', flexDirection: 'column', gap: '22px' }),
  field: styles({ display: 'flex', flexDirection: 'column', gap: '6px' }),
  compactField: styles({ width: '140px' }),
  mediumCompactField: styles({ width: '220px' }),
  compactTable: styles({ width: 'auto', maxWidth: 'fit-content', tableLayout: 'auto' }),
  rowButtons: styles({ display: 'flex', gap: '8px', flexWrap: 'wrap', alignItems: 'center' }),
  rowActionButtons: styles({ display: 'inline-flex', gap: '8px', flexWrap: 'nowrap', alignItems: 'center' }),
  topAlignedRowButtons: styles({ display: 'flex', gap: '8px', flexWrap: 'wrap', alignItems: 'flex-start' }),
  splitActions: styles({
    display: 'flex',
    gap: '12px',
    flexWrap: 'wrap',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  }),
  rightAlignedActions: styles({
    display: 'flex',
    gap: '8px',
    flexWrap: 'wrap',
    alignItems: 'flex-start',
    marginLeft: 'auto',
  }),
  actionGroup: styles({ display: 'flex', flexDirection: 'column', gap: '4px', alignItems: 'flex-start' }),
  compactParagraph: styles({ margin: '0' }),
  storageTable: styles({ width: '100%', borderCollapse: 'collapse' }),
  storageCellTop: styles({ verticalAlign: 'top', padding: '10px 12px', borderTop: '1px solid rgba(15, 23, 42, 0.08)' }),
  storageLabelCell: styles({ width: '220px', fontWeight: '600' }),
  storageDescriptionCell: styles({ minWidth: '280px' }),
  storageActionsCell: styles({ width: '320px' }),
  summaryGrid: styles({ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '12px' }),
  summaryItem: styles({
    backgroundColor: 'rgba(15, 23, 42, 0.03)',
    borderRadius: '8px',
    padding: '12px',
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  }),
  cardMutedText: styles({
    color: 'rgb(75, 85, 99)',
  }),
  hoverInfo: styles({
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    cursor: 'help',
  }),
  hoverInfoIcon: styles({
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '14px',
    height: '14px',
    borderRadius: '999px',
    border: '1px solid rgba(15, 23, 42, 0.2)',
    color: 'rgb(75, 85, 99)',
    fontSize: '10px',
    fontWeight: '700',
    lineHeight: '1',
    flexShrink: '0',
  }),
  inlineCode: styles({
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Consolas, monospace',
    backgroundColor: 'rgba(15, 23, 42, 0.04)',
    padding: '2px 6px',
    borderRadius: '6px',
  }),
  smallButton: styles({
    border: '1px solid rgba(15, 23, 42, 0.12)',
    backgroundColor: '#fff',
    color: '#0f172a',
    borderRadius: '8px',
    padding: '8px 10px',
    cursor: 'pointer',
  }),
  attentionButton: styles({
    border: '1px solid rgba(22, 101, 52, 0.55)',
    backgroundColor: 'rgba(134, 239, 172, 0.65)',
    color: '#166534',
    borderRadius: '8px',
    padding: '8px 10px',
    cursor: 'pointer',
    fontWeight: '600',
    boxShadow: 'inset 0 0 0 1px rgba(255, 255, 255, 0.35)',
  }),
  disabledButton: styles({
    border: '1px solid rgba(15, 23, 42, 0.08)',
    backgroundColor: 'rgba(15, 23, 42, 0.03)',
    color: 'rgba(15, 23, 42, 0.3)',
    borderRadius: '8px',
    padding: '8px 10px',
    cursor: 'not-allowed',
    opacity: '0.55',
    boxShadow: 'none',
  }),
  input: styles({
    border: '1px solid rgba(15, 23, 42, 0.12)',
    borderRadius: '8px',
    padding: '8px 10px',
    fontSize: '14px',
    width: '100%',
    backgroundColor: '#fff',
  }),
  warningBox: styles({
    border: '1px solid rgba(245, 158, 11, 0.3)',
    backgroundColor: 'rgba(245, 158, 11, 0.08)',
    borderRadius: '8px',
    padding: '12px',
  }),
  stickyWarningBox: styles({
    border: '1px solid rgba(153, 27, 27, 0.45)',
    backgroundColor: 'rgba(254, 226, 226, 0.92)',
    borderRadius: '8px',
    padding: '12px',
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    boxShadow: '0 10px 28px rgba(127, 29, 29, 0.12)',
    backdropFilter: 'blur(6px)',
  }),
  stickyWarningHeader: styles({
    display: 'flex',
    gap: '12px',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
  }),
  stickyWarningActions: styles({
    display: 'flex',
    gap: '8px',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginLeft: 'auto',
  }),
  stickyWarningTitle: styles({
    margin: '0',
    fontSize: '14px',
  }),
  stickyWarningList: styles({
    margin: '0',
    paddingLeft: '18px',
  }),
  errorBox: styles({
    border: '1px solid rgba(239, 68, 68, 0.3)',
    backgroundColor: 'rgba(239, 68, 68, 0.08)',
    borderRadius: '8px',
    padding: '12px',
  }),
  redNote: styles({
    color: 'rgb(153, 27, 27)',
  }),
  mismatchRow: styles({
    backgroundColor: 'rgba(254, 226, 226, 0.45)',
  }),
  highlightedColumn: styles({
    backgroundColor: 'rgba(187, 247, 208, 0.45)',
  }),
  highlightedHeaderColumn: styles({
    backgroundColor: 'rgba(187, 247, 208, 0.45)',
  }),
  blueHighlightedColumn: styles({
    backgroundColor: 'rgba(191, 219, 254, 0.45)',
  }),
  blueHighlightedHeaderColumn: styles({
    backgroundColor: 'rgba(191, 219, 254, 0.45)',
  }),
  rowErrorText: styles({
    color: 'rgb(153, 27, 27)',
    fontSize: '12px',
  }),
  historyCell: styles({
    padding: '12px',
    backgroundColor: 'rgba(15, 23, 42, 0.03)',
  }),
  historyTable: styles({
    width: '100%',
    borderCollapse: 'collapse',
  }),
  historyTableCell: styles({
    verticalAlign: 'top',
    padding: '8px 10px',
    borderTop: '1px solid rgba(15, 23, 42, 0.08)',
  }),
  historyDetailsCell: styles({
    whiteSpace: 'normal',
  }),
  listCompact: styles({ margin: '0', paddingLeft: '20px' }),
}
